import React, { useState } from 'react';
import { ShieldCheck, FileSpreadsheet, Copy, Check, Cpu, Database, Hash, Key, Activity, Clock } from 'lucide-react';
import { Violation } from '../../types/violation';

interface ReportMetadataFooterProps {
  totalViolations: number;
  totalStudents: number;
  violations: Violation[];
}

export const ReportMetadataFooter: React.FC<ReportMetadataFooterProps> = ({
  totalViolations,
  totalStudents,
  violations,
}) => {
  const [copied, setCopied] = useState(false);

  const reportId = `REP-${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}${String(new Date().getDate()).padStart(2, '0')}-9842`;
  const digitalSignature = '0x8F92A1B39F7E419E7C20D418B12';

  const handleCopyLink = () => {
    navigator.clipboard.writeText(`https://attendguard.university.edu/verify/${reportId}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportCsv = () => {
    let csvRows = ["Roll No,Student Name,Violation Type,Location,Department,Status,Date"];
    violations.forEach((v) => {
      csvRows.push(
        `"${v.roll_no}","${v.student_name || ''}","${v.type}","${v.location}","${v.department}","${v.status}","${v.created_at || v.date || ''}"`
      );
    });
    const csvContent = "data:text/csv;charset=utf-8," + csvRows.join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `AttendGuard_Audit_Report_${reportId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="glass-panel p-5 sm:p-7 rounded-[22px] shadow-lg border border-white/40 dark:border-white/10 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-black/5 dark:border-white/10">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-[#30D158]/15 border border-[#30D158]/30 text-[#30D158] flex items-center justify-center">
            <ShieldCheck className="w-4 h-4" strokeWidth={2} />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-800 dark:text-white flex items-center gap-2">
              Official Institutional Audit Certificate
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-[#30D158]/15 text-[#30D158]">
                AUTHENTICATED
              </span>
            </h3>
            <p className="text-xs text-slate-500 font-medium">
              Tamper-evident administrative audit ledger
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleExportCsv}
            className="apple-btn-secondary px-3.5 py-1.5 rounded-xl text-xs font-bold flex items-center gap-1.5"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-[#30D158]" />
            <span>Export CSV ({violations.length})</span>
          </button>

          <button
            onClick={handleCopyLink}
            className="apple-btn-primary px-3.5 py-1.5 rounded-xl text-xs font-bold flex items-center gap-1.5 shadow-xs"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5 text-white" />}
            <span>{copied ? 'Copied Verification' : 'Share Link'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3 text-xs">
        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Hash className="w-3 h-3 text-[#007AFF]" /> Report ID
          </span>
          <p className="font-bold text-slate-800 dark:text-slate-200 font-mono">
            {reportId}
          </p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Key className="w-3 h-3 text-[#BF5AF2]" /> Generated By
          </span>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            Administrator
          </p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Clock className="w-3 h-3 text-[#FF9F0A]" /> Total DB Records
          </span>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            {totalViolations} Violations / {totalStudents} Students
          </p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Cpu className="w-3 h-3 text-[#30D158]" /> AI Engine
          </span>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            v4.2.0-CV Executive
          </p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Database className="w-3 h-3 text-[#64D2FF]" /> Database
          </span>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            MongoDB v7.0.5 GuardDB
          </p>
        </div>

        <div className="space-y-0.5 col-span-2 sm:col-span-2">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <ShieldCheck className="w-3 h-3 text-[#30D158]" /> Signature
          </span>
          <p className="font-mono text-[11px] font-semibold text-slate-500 truncate">
            {digitalSignature}
          </p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400">Last Updated</span>
          <p className="font-semibold text-slate-800 dark:text-slate-200">Just now</p>
        </div>

        <div className="space-y-0.5">
          <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1">
            <Activity className="w-3 h-3 text-[#30D158]" /> System Health
          </span>
          <p className="font-bold text-[#30D158] flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#30D158] animate-pulse" />
            99.98% Operational
          </p>
        </div>
      </div>
    </div>
  );
};
